#!/usr/bin/env python3
"""
Regenerates rss.xml and share/*.html straight from whatever Field Notes and
Research entries currently exist in index.html. No separate data to maintain —
this reads the same HTML the site itself renders, so it can't drift out of sync.

Run automatically by .github/workflows/sync-derived-files.yml on every push that
touches index.html. Can also be run locally / manually any time:
    pip install beautifulsoup4
    python3 scripts/generate_derived_files.py
"""
import re, os
from datetime import datetime, timedelta, timezone
from xml.sax.saxutils import escape
from bs4 import BeautifulSoup

SITE = "https://jishnuec.github.io/"
IST = timezone(timedelta(hours=5, minutes=30))
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "index.html")
SHARE_DIR = os.path.join(ROOT, "share")
RSS_PATH = os.path.join(ROOT, "rss.xml")


def slugify(text):
    # mirrors the site's own client-side slugify() exactly, so ids always match
    t = text.lower()
    t = re.sub(r'[^a-z0-9\s-]', '', t)
    t = t.strip()
    words = [w for w in re.split(r'\s+', t) if w][:6]
    return re.sub(r'-+', '-', '-'.join(words))


def truncate(text, n=155):
    text = re.sub(r'\s+', ' ', text).strip()
    if len(text) <= n:
        return text
    cut = text[:n].rsplit(' ', 1)[0]
    return cut.rstrip(',.;\u2014-') + '\u2026'


def rfc822(date_str):
    d = datetime.strptime(date_str, "%Y-%m-%d").replace(hour=9, tzinfo=IST)
    return d.strftime('%a, %d %b %Y %H:%M:%S %z')


with open(INDEX, encoding="utf-8") as f:
    soup = BeautifulSoup(f.read(), "html.parser")

notes = []
for el in soup.select("#fnFeed .fn-post[data-date]"):
    date = (el.get("data-date") or "").strip()
    title_el = el.select_one(".fn-title")
    body_el = el.select_one(".fn-body")
    img_el = el.select_one(".fn-img-wrap img")
    if not date or not title_el:
        continue
    notes.append({
        "date": date,
        "title": title_el.get_text(strip=True),
        "body": body_el.get_text(" ", strip=True) if body_el else "",
        "findings": [f.get_text(" ", strip=True) for f in el.select(".fn-finding")],
        "image": (img_el.get("src") or "").strip() if img_el else "",
    })

papers = []
for el in soup.select("#resGrid .rcard[data-date]"):
    date = (el.get("data-date") or "").strip()
    title_el = el.select_one(".rtitle")
    desc_el = el.select_one(".rdesc")
    if not date or not title_el:
        continue
    papers.append({
        "date": date,
        "title": title_el.get_text(strip=True),
        "desc": desc_el.get_text(" ", strip=True) if desc_el else "",
        "image": "",  # research cards don't carry their own image in the source markup
    })

notes.sort(key=lambda e: e["date"], reverse=True)
papers.sort(key=lambda e: e["date"], reverse=True)

# ---------------------------------------------------------------- rss.xml --
items_xml = []
for e in notes:
    anchor = f"note-{e['date']}-{slugify(e['title'])}"
    link = f"{SITE}#{anchor}"
    desc_html = f"<p>{e['body']}</p>"
    if e["findings"]:
        desc_html += "<ul>" + "".join(f"<li>{x}</li>" for x in e["findings"]) + "</ul>"
    desc_html = desc_html.replace("]]>", "]] >")
    items_xml.append(f"""  <item>
    <title>{escape(e['title'])}</title>
    <link>{link}</link>
    <guid isPermaLink="true">{link}</guid>
    <pubDate>{rfc822(e['date'])}</pubDate>
    <description><![CDATA[{desc_html}]]></description>
  </item>""")

now = datetime.now(IST).strftime('%a, %d %b %Y %H:%M:%S %z')
rss = f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
  <title>Jishnu EC \u2014 Field Notes</title>
  <link>{SITE}</link>
  <atom:link href="{SITE}rss.xml" rel="self" type="application/rss+xml"/>
  <description>Field notes from Jishnu EC \u2014 SOC simulations, DFIR labs, CTF write-ups, and pentesting practice, logged as they happen.</description>
  <language>en-us</language>
  <lastBuildDate>{now}</lastBuildDate>
  <generator>auto-generated by scripts/generate_derived_files.py</generator>
{chr(10).join(items_xml)}
</channel>
</rss>
"""
with open(RSS_PATH, "w", encoding="utf-8") as f:
    f.write(rss)

# ------------------------------------------------------------ share/*.html --
os.makedirs(SHARE_DIR, exist_ok=True)

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta http-equiv="refresh" content="0; url={target}"/>
<title>{title} | Jishnu EC</title>
<meta name="robots" content="noindex"/>
<link rel="canonical" href="{target}"/>
<meta property="og:type" content="article"/>
<meta property="og:url" content="{page_url}"/>
<meta property="og:title" content="{title}"/>
<meta property="og:description" content="{desc}"/>
<meta property="og:image" content="{image}"/>
{dims}<meta property="og:site_name" content="Jishnu EC"/>
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:title" content="{title}"/>
<meta name="twitter:description" content="{desc}"/>
<meta name="twitter:image" content="{image}"/>
<link rel="icon" type="image/png" sizes="32x32" href="../icons/icon-32.png"/>
<style>
body{{background:#020d02;color:#eeffee;font-family:'Share Tech Mono',monospace;min-height:100vh;display:flex;align-items:center;justify-content:center;text-align:center;padding:2rem}}
a{{color:#00ff41}}
</style>
</head>
<body>
<p>Redirecting to the full entry&hellip; <a href="{target}">click here if you're not redirected</a>.</p>
<script>window.location.replace('{target}');</script>
</body>
</html>
"""

valid_ids = set()


def emit(prefix, items, desc_key):
    for e in items:
        id_ = f"{prefix}-{e['date']}-{slugify(e['title'])}"
        valid_ids.add(id_)
        target = f"{SITE}#{id_}"
        # use the entry's own screenshot when it has one; otherwise fall back to the
        # generic branded image (whose exact 1200x630 dimensions we can safely declare)
        img = e.get("image") or ""
        if img:
            image_url = img
            dims = ""
        else:
            image_url = f"{SITE}og-image.png"
            dims = '<meta property="og:image:width" content="1200"/>\n<meta property="og:image:height" content="630"/>\n'
        html = TEMPLATE.format(
            target=target,
            title=e["title"].replace('"', '&quot;'),
            desc=truncate(e[desc_key]).replace('"', '&quot;'),
            image=image_url,
            dims=dims,
            page_url=f"{SITE}share/{id_}.html",
        )
        with open(os.path.join(SHARE_DIR, f"{id_}.html"), "w", encoding="utf-8") as f:
            f.write(html)


emit("note", notes, "body")
emit("paper", papers, "desc")

removed = 0
for fn in os.listdir(SHARE_DIR):
    if fn.endswith(".html") and fn[:-5] not in valid_ids:
        os.remove(os.path.join(SHARE_DIR, fn))
        removed += 1

print(f"rss.xml: {len(notes)} items | share/: {len(valid_ids)} pages written, {removed} stale page(s) removed")